#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(bspc query -M --names) = "DisplayPort-0" ]]; then
	bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9 0
else 
	bspc monitor DisplayPort-0 -d 1 2 3 4 5 
	bspc monitor HDMI-A-1 -d 6 7 8 9 0 
fi

# Swaps the monitors so my workspaces are on main hdmi monitor
#bspc monitor HDMI-A-1 -s DisplayPort-0

bspc config border_width         5 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#afedec'

bspc config external_rules_command "$HOME/dotfiles/bspwm/external_rules_spotify.sh"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating
bspc rule -a Brave-browser desktop="1"
bspc rule -a Steam desktop="3"
bspc rule -a discord desktop="2"
bspc rule -a Spotify desktop="6"

# got the window name using "xprop | grep WM_CLASS" and clicking window, in this case godslayer was the name
bspc rule -a godslayer state=floating
#bspc rule -a steam state=floating focus=on

mygames=$(ls ~/.steam/steam/steamapps | grep appmanifest | sed 's/[^0-9]*//g')
 # this sed command removes everything but the digits

for game in $mygames; do
        bspc rule -a steam_app_$game desktop=^10 state=fullscreen follow=on
done

$HOME/dotfiles/polybar/launch.sh
