#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 1 2 3 4 5 
bspc monitor DVI-D-0 -d 6 7 8 9 0 

# Swaps the monitors so my workspaces are on main hdmi monitor
bspc monitor DVI-D-0 -s HDMI-0

bspc config border_width         5 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#afedec'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating
#bspc rule -a steam state=floating focus=on

#mygames=$(ls ~/.steam/steam/steamapps | grep appmanifest | sed 's/[^0-9]*//g')
# this sed command removes everything but the digits

#for game in $mygames; do
#        bspc rule -a steam_app_$game desktop=^10 state=fullscreen follow=on
#done

$HOME/.config/polybar/launch.sh 
